afrikaquiz/urls.py
from django.urls import path

from . import views

app_name = 'afrikaquiz'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('longest/', views.longest, name='longest'),
    path('list/', views.IndexView.as_view(), name='list'),
    path('random/', views.random, name='random'),
    path('country/<str:iso>/', views.detail, name='detail'),
    path('country/<str:iso>/<int:pid>/result/',views.result, name='result'),
    path('country/<str:iso>/vote', views.vote, name='vote'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('statistikk/', include('statistikk.urls')),
    path('afrikaquiz/', include('afrikaquiz.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/',views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

#urlpatterns = [
#    # ex /polls/
#    path('', views.index, name='index'),
#    # ex: /polls/5
#    path('<int:question_id>/', views.detail, name='detail'),
#    # ex: /polls/5/results/
#    path('<int:question_id>/results/', views.results, name='results'),
#    # ex: /polls/5/vote/
#    path('<int:question_id>/vote/', views.vote, name='vote')
#]

afrikaquiz/models.py
from django.db import models

from random import sample, shuffle

# Parent classes
class Result(models.Model):
    '''Placeholder'''

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name


class Country(models.Model):
    iso = models.CharField(max_length=3,primary_key=True)
    name= models.CharField(max_length=200)
    leaders = models.ManyToManyField(Person,through='Leadership')
    def __str__(self):
        return self.iso + ": " + self.name
    def get_leader(self):
        return Leadership.objects.filter(country=self,end__isnull=True).first().person
    def get_title(self):
        return Leadership.objects.filter(country=self,end__isnull=True).first().title
    def get_alternatives(self,n):
        correct = self.get_leader()
        alternatives = [correct]
        t_wrong = list(Person.objects.exclude(pk=correct.pk))
        if len(t_wrong) < n-1: n = len(t_wrong)+1
        wrong = sample(t_wrong,max(n-1,0))
        alternatives.extend(wrong)
        shuffle(alternatives)
        return alternatives
    class Meta:
        verbose_name_plural = "countries"

class Leadership(models.Model):
    person = models.ForeignKey(Person,on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, default="president")
    start = models.DateField()
    end = models.DateField(blank=True, null=True)

    def __str__(self):
        if self.end:
            endtext=str(self.end.year)
        else:
            endtext=""
        return self.country.name + " (" + self.country.iso + "): " + self.person.name + "(" + str(self.start.year) + " - " + endtext + ")"

class Leadership_result(models.Model):
    person = models.ForeignKey(Person,on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.country.name + " (" + self.country.iso + "): " + self.person.name + " (" + str(self.votes) + ")"

afrikaquiz/controller.py
from models import Country, Person

class Question():
    '''todo'''
    def __init__(self, country)
        self.country = country
        self.alternatives = self.generate_alternatives()
        self.text = "Hva heter statsoverhodet i " + Country.name + "?"
    def generate_alternatives(self):
        alt = [self.country.get_leader]

class Question_set():
    '''todo'''
class Quiz_instance():
    '''todo'''

afrikaquiz/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from random import sample

# Create your views here.

from afrikaquiz.models import *

ALTERNATIVE_COUNT = 4

class IndexView(generic.ListView):
    template_name = 'afrikaquiz/index.html'
    context_object_name ='latest_question_list'

    def get_queryset(self):
        return Country.objects.all()

def result(request, iso, pid):
    country = get_object_or_404(Country,iso=iso)
    correct_person = country.get_leader()
    selected_person = Person.objects.get(pk=pid)
    alternativer = Leadership_result.objects.filter(country=country).order_by('-votes')
    return render(request, 'afrikaquiz/result.html', { 'country':country, 'selected_person': selected_person, 'correct_person': correct_person, 'alternativer': alternativer})

def longest(request):
    leadership = Leadership.objects.filter(end__isnull=True).order_by('start')
    return render(request, 'afrikaquiz/longest.html', {'leadership':leadership})

def detail(request, iso):
    country = get_object_or_404(Country,iso=iso)
    title = country.get_title()
    alternatives = country.get_alternatives(ALTERNATIVE_COUNT)
    return render(request, 'afrikaquiz/detail.html', { 'alternatives':alternatives, 'country': country, 'title':title})

def random(request):
    country = sample(list(Country.objects.all()), 1)[0]
    title = country.get_title()
    alternatives = country.get_alternatives(ALTERNATIVE_COUNT)
    return render(request, 'afrikaquiz/detail.html', { 'alternatives':alternatives, 'country': country, 'title':title})

def vote(request, iso):
    country = get_object_or_404(Country,iso=iso)
    alternatives = country.get_alternatives(ALTERNATIVE_COUNT)
    try:
        selected_person = Person.objects.get(pk=request.POST['choice'])
    except (KeyError, Person.DoesNotExist):
        #Redisplay the question voting form
        return render(request, 'afrikaquiz/detail.html', { 'alternatives':alternatives, 'country': country, 'error_message':"You didn't select a choice."})
    else:
        lr = Leadership_result.objects.get_or_create(country=country,person=selected_person)[0]
        lr.votes += 1
        lr.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('afrikaquiz:result',args=(iso,selected_person.id)))

afrikaquiz/templates/afrikaquiz/detail.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
  <title>Magdalon's African Quiz</title>
</head>
<body>
<h1>Magdalon's African Quiz</h1>
<p>Who is the {{title}} of {{ country.name }}?</p>
{% if error_message %}<p>
   <strong>{{error_message}}</strong>
</p>
{% endif %}

<form  class="pure-form" action="{% url 'afrikaquiz:vote' country.iso %}" method ="post">
  {% csrf_token %}
  {% for person in alternatives %}
  <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ person.id }}" />
  <label for="choice{{forloop.counter}}">{{person.name}}</label><br />
  {% endfor %}
  <input type="submit" value="Vote" />
</form>

</body>
</html>

afrikaquiz/templates/afrikaquiz/index.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
  <title>Magdalon's African Quiz</title>
</head>
<body>
{% load static %}
<h1>Magdalon's African Quiz</h1>
<p>
  Can you pick the leader of a <a href="{% url 'afrikaquiz:random' %}">random African country</a>?
</p>
<p>
  Or choose a country below:
</p>
{% if latest_question_list %}
<ul>
  {% for country in latest_question_list %}
  <li>
    <a href="{% url 'afrikaquiz:detail' country.iso %}"> {{ country.name }} </a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>
  No countries are available.
</p>
{% endif %}
</body>
</html>

afrikaquiz/templates/afrikaquiz/longest.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
  <title>Magdalon's African Quiz</title>
</head>
<body>
{% load static %}
<h1>Magdalon's African quiz</h1>
<h1>Longest serving leaders in africa</h1>
<table class="pure-table pure-table-bordered">
<thead>
  <tr>
    <th>
      #
    </th>
    <th>
      Country
    </th>
    <th>
      Name
    </th>
    <th>
      Since
    </th>
    <th>
      Duration
    </th>
  </tr>

</thead>
<tbody>
  {% for leader in leadership %}
  <tr>
    <td>
      {{forloop.counter}}
    </td>
    <td>{{leader.country.name}}</td>
    <td>
      {{leader.person.name}}
    </td>
    <td>
      {{leader.start.year}}
    </td>
    <td>

    </td>
  </tr>
  {% endfor %}
</tbody>
</table>


</body>
</html>

afrikaquiz/templates/afrikaquiz/result.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
  <title>Magdalon's African Quiz</title>
</head>
<body>
<h1>{{ country.name }}</h1>

<p>
  <b>You answered:</b> {{selected_person}}
</p>
<p>
  <b>Correct answer:</b> {{correct_person}}
</p>
<p>
  {% if selected_person == correct_person %}
    Congratulations. You are correct!
  {% else %}
    Sorry. You are wrong.
  {% endif %}
</p>
<p>
  <a href="{% url 'afrikaquiz:detail' country.iso %}">Try again?</a> | <a href="{% url 'afrikaquiz:random' %}">Next country!</a>
</p>
<hr />
<h2>Others have answered:</h2>
<table class="pure-table pure-table-bordered">
  <tr>
    <th>
      #
    </th>
    <th>
      Navn
    </th>
    <th>
      Stemmer
    </th>
  </tr>
  {% for lr in alternativer %}
  <tr>
    <td>
      {{forloop.counter}}
    </td>

    <td>
      {{ lr.person.name }}
    </td>

    <td>
      {{ lr.votes }}
    </td>
  </tr>
  {% endfor %}
</table>
<hr />
<h2>Leadership history</h2>
{% if history %}

  <table class="pure-table pure-table-bordered">
    <tr>
      <th>
        Name
      </th>
      <th>
        from
      </th>
      <th>
        to
      </th>
    </tr>
    {% for leader in history %}
    <tr>
      <td>
        leader.name
      </td>
      <td>
        leader.from
      </td>
      <td>
        leader.to
      </td>
    </tr>
    {% endfor %}
  </table>
{% else %}
<p>
  No history available.
</p>
{% endif %}
</body>
</html>